### ISSUE TITLE
Issues with macos

### ISSUE THREAD

**Issue by yogipatel5** [gabfv/logitech-g-hub-settings-extractor#4]
This program is intended to extract and replace the settings.json inside the settings.db used by Logitech G Hub.

Press Enter to continue.

Traceback (most recent call last):
  File "ghub-settings.py", line 173, in <module>
    input()
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing

**Comment by gabfv** [comment]
I don't have a mac to test it, but did you press just Enter after the message or something else?
Anyway, I've made a modification to the script, can you update and test it again?

**Comment by gabfv** [comment]
Also, what's your Python version?
